services:
  tg-bot:
    build: .
    container_name: at_spider
    restart: unless-stopped
    # ğŸŒŸ ç«¯å£ä¿®æ”¹ä¸º 8877
    ports:
      - "8877:8877"
    volumes:
      - /vol1/1000/docker/at_spider/data:/app/data
    environment:
      - TZ=Asia/Shanghai
      # ğŸ‘‡ğŸ‘‡ğŸ‘‡ åœ¨è¿™é‡Œä¿®æ”¹ç‰ˆæœ¬å·ï¼Œç½‘é¡µé¡µè„šä¼šè‡ªåŠ¨åŒæ­¥ ğŸ‘‡ğŸ‘‡ğŸ‘‡
      - APP_VERSION=v1.0.0 Pro